Client/Models/ErrorViewModel.cs
using System;

namespace Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using API.Models;
using Client.Base;
using Client.Repositories.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    [Authorize]
    public class EmployeeController : BaseController<Employee, EmployeeRepository, string>
    {
        private readonly EmployeeRepository repository;
        public EmployeeController(EmployeeRepository repository) : base(repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Employees/GetData")]
        public async Task<JsonResult> GetData()
        {
            var NIK = HttpContext.Session.GetString("NIK");
            var result = await repository.GetRegisterByNIK(NIK);
            return Json(result);
        }
    }
}

Client/Controllers/EmployeeRequestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize(Roles = "Admin, Manager, Finance")]
    public class EmployeeRequestController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }

        public IActionResult ValidateBonus()
        {
            return View();
        }
    }
}

Client/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult NotFound404()
        {
            return View();
        }

        public IActionResult Unauthorized401()
        {
            return View();
        }

        public IActionResult Forbidden403()
        {
            return View();
        }
    }
}

Client/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Client.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Client.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult OvertimeRequest()
        {
            return View();
        }

        public IActionResult OvertimeHistory()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Client/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using API.Models;
using Client.Base;
using Client.Repositories.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using API.ViewModel;
using Microsoft.AspNetCore.Authorization;
using System.IdentityModel.Tokens.Jwt;

namespace Client.Controllers
{
    public class LoginController : BaseController<Account, AccountRepository, string>
    {
        private readonly AccountRepository repository;
        public LoginController(AccountRepository repository) : base(repository)
        {
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var token = HttpContext.Session.GetString("JWToken");

            if (token == null)
            {
                return View();
            }

            return RedirectToAction("index", "Home");
        }
        public IActionResult ForgotPassword()
        {
            return View();
        }
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public JsonResult ForgotPassword(ForgotPasswordVM forgotPasswordVM)
        {
            var result = repository.ForgotPassword(forgotPasswordVM);
            return Json(result);
        }

        [HttpPut]
        public JsonResult ChangePassword(ChangePasswordVM changePasswordVM)
        {
            var result = repository.ChangePassword(changePasswordVM);
            return Json(result);
        }

        [HttpPost("Login/Auth")]
        public async Task<IActionResult> Auth(LoginVM loginVM)
        {
            var jwtToken = await repository.Auth(loginVM);
            var token = jwtToken.idtoken;

            if (token == null)
            {
                //return RedirectToAction("index");
                TempData["message"] = jwtToken.message;
                return RedirectToAction("index", "Login"); //untuk return ke halaman Employees/Login.cshtml

            }
            var handler = new JwtSecurityTokenHandler();
            var decodedValue = handler.ReadJwtToken(token);

            var nik = decodedValue.Claims.First(c => c.Type == "nik").Value;

            HttpContext.Session.SetString("JWToken", token);
            HttpContext.Session.SetString("NIK", nik);
            return RedirectToAction("index", "Home");
        }

        [Authorize]
        [HttpGet("Logout/")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("index", "Login");
        }
    }
}

Client/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class ManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/OvertimeHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class OvertimeHistoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/RequestFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using API.Models;
using Client.Base;
using Client.Repositories.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    [Authorize]
    public class RequestFormController : BaseController<Employee, EmployeeRepository, string>
    {
        private readonly EmployeeRepository repository;
        public RequestFormController(EmployeeRepository repository) : base(repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Employees/GetData")]
        public async Task<JsonResult> GetData()
        {
            var NIK = HttpContext.Session.GetString("NIK");
            var result = await repository.GetRegisterByNIK(NIK);
            return Json(result);
        }

        [HttpGet("Employees/GetOvertimeHistory")]
        public async Task<JsonResult> GetOvertimeHistory()
        {
            var NIK = HttpContext.Session.GetString("NIK");
            var result = await repository.GetOvertimeHistory(NIK);
            return Json(result);
        }
    }
}

Client/Views/Employee/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_AdminLayout";
}
<div class="section-header d-flex justify-content-center shadow">
    <h1>Dashboard</h1>
</div>
<div class="section-body">
    <div class="container">
        <div class="row ustify-content-center">
            <div class="col">
                <div class="card shadow-lg position-absolute" style="width: 18rem;">
                    <img class="card-img-top" src="~/img/undraw_pull_request_gld8.png" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Overtime Request</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-lg ml-md-auto" style="width: 18rem;">
                    <img class="card-img-top" src="~/img/undraw_Spreadsheet_re_cn18.png" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Overtime History</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Client/Views/EmployeeRequest/Index.cshtml
@{
    ViewData["Title"] = "Employee Request";
    Layout = "_AdminLayout";
}

<section class="section">
    <div class="section-header">
        <h1>Employee Request</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h4>Request Data</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="tableRequest">
                                <thead>
                                    <tr>
                                        <th class="text-center">
                                            No
                                        </th>
                                        <th>NIK</th>
                                        <th>Name</th>
                                        <th>Date</th>
                                        <th>Start-Time</th>
                                        <th>End-Time</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="detailModalRequest">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Detail Request</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="respon" class="needs-validation" novalidate>
                    <div class="form-row">
                        <div class="col-md mb-3">
                            <label for="nik">NIK: </label>
                            <input type="text" class="form-control" id="nikModal" value="" readonly>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label for="fullname">Fullname: </label>
                            <input type="text" class="form-control" id="fullNameModal" value="" readonly>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label for="date">Date: </label>
                            <input type="date" class="form-control" id="dateModal" value="" readonly>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md mb-3">
                            <label for="startTime">Start Time: </label>
                            <input type="time" class="form-control" id="startTimeModal" value="" readonly>
                        </div>
                        <div class="col-md mb-3">
                            <label for="endTime">End Time: </label>
                            <input type="time" class="form-control" id="endTimeModal" value="" readonly>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label for="note">Job Note: </label>
                            <textarea type="text" class="form-control" id="noteModal" value="Test" readonly></textarea>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <label for="managerNote">Manager Note: </label>
                            <textarea type="text" class="form-control" id="managerNoteModal" value="no"></textarea>
                        </div>
                    </div>
                </form>
                    <div class="d-inline-block mt-3">
                        <button id="acceptRequest" class="btn btn-success ml-2" type="button" onclick="acceptRequest()"> Accept</button>
                        <button id="rejectRequest" class="btn btn-danger ml-2" type="button" onclick="rejectRequest()"> Reject</button>
                    </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/js/Manager.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
}

Client/Views/EmployeeRequest/ValidateBonus.cshtml
@{
    ViewData["Title"] = "Employee Request";
    Layout = "_AdminLayout";
}

<section class="section">
    <div class="section-header">
        <h1>Employee Request</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h4>Request Data</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="tableValidateBonus">
                                <thead>
                                    <tr>
                                        <th class="text-center">
                                            No
                                        </th>
                                        <th>NIK</th>
                                        <th>Name</th>
                                        <th>Date</th>
                                        <th>Start-Time</th>
                                        <th>End-Time</th>
                                        <th>Salary</th>
                                        <th>TotalFee</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script src="~/js/Finance.js" asp-append-version="true"></script>
}

Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_AdminLayout";
}

<section class="section">
    <div class="section-header d-flex justify-content-center shadow">
        <h1>Dashboard</h1>
    </div>
    <div class="row">
        <div class="col-12 mb-4">
            <div class="hero bg-primary text-white">
                <div class="hero-inner">
                    <h2>Overtime Request</h2>
                    <p class="lead">You can request overtime by click the button below</p>
                    <div class="mt-4">
                        <a href="/RequestForm" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="far fa-user"></i>Go</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 mb-4">
            <div class="hero bg-primary text-white">
                <div class="hero-inner">
                    <h2>Request History</h2>
                    <p class="lead">You can see your request history by click the button below</p>
                    <div class="mt-4">
                        <a href="#" class="btn btn-outline-white btn-lg btn-icon icon-left"><i class="far fa-user"></i>Go</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Client/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Blank Page — Stisla</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="~/lib/assets/modules/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/assets/modules/fontawesome/css/all.min.css">

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="~/lib/assets/modules/datatables/datatables.min.css">
    <link rel="stylesheet" href="~/lib/assets/modules/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/assets/modules/datatables/Select-1.2.4/css/select.bootstrap4.min.css">

    <!-- Template CSS -->
    <link rel="stylesheet" href="~/lib/assets/css/style.css">
    <link rel="stylesheet" href="~/lib/assets/css/components.css">
    <link rel="stylesheet" href="~/css/site.css">
    <!-- Start GA -->
    <script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script>
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-94034622-3');</script>
    <!-- /END GA -->
</head>

<body>
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            <div class="navbar-bg"></div>
            <nav class="navbar navbar-expand-lg main-navbar">
                <form class="form-inline mr-auto">
                    <ul class="navbar-nav mr-3">
                        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
                        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
                    </ul>
                </form>
                <ul class="navbar-nav navbar-right">
                    <li class="dropdown dropdown-list-toggle">
                        <a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
                        <div class="dropdown-menu dropdown-list dropdown-menu-right">
                            <div class="dropdown-header">
                                Notifications
                                <div class="float-right">
                                    <a href="#">Mark All As Read</a>
                                </div>
                            </div>
                            <div class="dropdown-list-content dropdown-list-icons">
                                <a href="#" class="dropdown-item dropdown-item-unread">
                                    <div class="dropdown-item-icon bg-primary text-white">
                                        <i class="fas fa-code"></i>
                                    </div>
                                    <div class="dropdown-item-desc">
                                        Template update is available now!
                                        <div class="time text-primary">2 Min Ago</div>
                                    </div>
                                </a>
                                <a href="#" class="dropdown-item">
                                    <div class="dropdown-item-icon bg-info text-white">
                                        <i class="far fa-user"></i>
                                    </div>
                                    <div class="dropdown-item-desc">
                                        <b>You</b> and <b>Dedik Sugiharto</b> are now friends
                                        <div class="time">10 Hours Ago</div>
                                    </div>
                                </a>
                                <a href="#" class="dropdown-item">
                                    <div class="dropdown-item-icon bg-success text-white">
                                        <i class="fas fa-check"></i>
                                    </div>
                                    <div class="dropdown-item-desc">
                                        <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                                        <div class="time">12 Hours Ago</div>
                                    </div>
                                </a>
                                <a href="#" class="dropdown-item">
                                    <div class="dropdown-item-icon bg-danger text-white">
                                        <i class="fas fa-exclamation-triangle"></i>
                                    </div>
                                    <div class="dropdown-item-desc">
                                        Low disk space. Let's clean it!
                                        <div class="time">17 Hours Ago</div>
                                    </div>
                                </a>
                                <a href="#" class="dropdown-item">
                                    <div class="dropdown-item-icon bg-info text-white">
                                        <i class="fas fa-bell"></i>
                                    </div>
                                    <div class="dropdown-item-desc">
                                        Welcome to Stisla template!
                                        <div class="time">Yesterday</div>
                                    </div>
                                </a>
                            </div>
                            <div class="dropdown-footer text-center">
                                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                            <img alt="image" src="~/lib/assets/img/avatar/avatar-1.png" class="rounded-circle mr-1">
                            <div class="d-sm-none d-lg-inline-block">Hi, <span id="userName"></span></div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <div class="dropdown-title">NIK: <span id="nikUser2"></span></div>
                            <a href="features-profile.html" class="dropdown-item has-icon">
                                <i class="far fa-user"></i> Profile
                            </a>
                            <a href="features-activities.html" class="dropdown-item has-icon">
                                <i class="fas fa-bolt"></i> Activities
                            </a>
                            <a href="features-settings.html" class="dropdown-item has-icon">
                                <i class="fas fa-cog"></i> Settings
                            </a>
                            <div class="dropdown-divider"></div>
                            <a href="../Logout" class="dropdown-item has-icon text-danger">
                                <i class="fas fa-sign-out-alt"></i> Logout
                            </a>
                        </div>
                    </li>
                </ul>
            </nav>
            <div class="main-sidebar sidebar-style-2" tabindex="1" style="overflow: hidden; outline: none;">
                <aside id="sidebar-wrapper">
                    <div class="sidebar-brand">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Overtime Request</a>
                    </div>
                    <div class="sidebar-brand sidebar-brand-sm">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">OR</a>
                    </div>
                    <ul class="sidebar-menu">
                        <li class="menu-header">Dashboard</li>
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link"><i class="fas fa-fire"></i><span>Dashboard</span></a>
                        </li>
                        <li class="menu-header">Menu</li>
                        <li class="dropdown">
                            <a href="#" class="nav-link has-dropdown"><i class="far fa-file-alt"></i><span>Menu</span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a asp-area="" asp-controller="RequestForm" asp-action="Index" class="nav-link"><span>Request Form</span></a>
                                </li>
                                @if ((User.IsInRole("Manager")) || (User.IsInRole("Admin")))
                                {
                                    <li>
                                        <a asp-area="" asp-controller="EmployeeRequest" asp-action="Index" class="nav-link"><span>Employee Request (M)</span></a>
                                    </li>
                                }
                                @if ((User.IsInRole("Finance")) || (User.IsInRole("Admin")))
                                {
                                    <li>
                                        <a asp-area="" asp-controller="EmployeeRequest" asp-action="ValidateBonus" class="nav-link"><span>Employee Request (F)</span></a>
                                    </li>
                                }
                                <li>
                                    <a asp-area="" asp-controller="OvertimeHistory" asp-action="Index" class="nav-link"><span>Overtime Request History</span></a>
                                </li>
                            </ul>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="menu-header">Manage APP</li>
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="ManageUser" class="nav-link"><i class="far fa-user"></i><span>Manage User</span></a>
                            </li>
                        }


                    </ul>
                </aside>
            </div>

            <!-- Main Content -->
            <div class="main-content" style="min-height: 562px;">
                @RenderBody()
            </div>
            <footer class="main-footer">
                <div class="text-center">
                    &copy; 2022 -  PT Mitra Integrasi Informatika. All Rights Reserved.
                </div>
                <div class="footer-right">

                </div>
            </footer>
        </div>
    </div>

    <!-- General JS Scripts -->
    <script src="~/lib/assets/modules/jquery.min.js"></script>
    <script src="~/lib/assets/modules/popper.js"></script>
    <script src="~/lib/assets/modules/tooltip.js"></script>
    <script src="~/lib/assets/modules/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/assets/modules/nicescroll/jquery.nicescroll.min.js"></script>
    <script src="~/lib/assets/modules/moment.min.js"></script>
    <script src="~/lib/assets/js/stisla.js"></script>

    <!-- JS Libraies -->
    <script src="~/lib/assets/modules/datatables/datatables.min.js"></script>
    <script src="~/lib/assets/modules/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/assets/modules/datatables/Select-1.2.4/js/dataTables.select.min.js"></script>
    <script src="~/lib/assets/modules/jquery-ui/jquery-ui.min.js"></script>

    <!-- Page Specific JS File -->
    <script src="~/lib/assets/js/page/modules-datatables.js"></script>

    <!-- Template JS File -->
    <script src="~/lib/assets/js/scripts.js"></script>
    <script src="~/lib/assets/js/custom.js"></script>

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.html5.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.colVis.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.print.min.js"></script>
    <script src="~/js/Manager.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.4/dist/sweetalert2.all.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.4/dist/sweetalert2.min.js"></script>

    @RenderSection("Scripts", required: false)

    <div id="ascrail2000" class="nicescroll-rails nicescroll-rails-vr" style="width: 8px; z-index: 892; cursor: default; position: fixed; top: 0px; left: 242px; height: 657px; opacity: 0;"><div class="nicescroll-cursors" style="position: relative; top: 0px; float: right; width: 6px; height: 432px; background-color: rgb(66, 66, 66); border: 1px solid rgb(255, 255, 255); background-clip: padding-box; border-radius: 5px;"></div></div><div id="ascrail2000-hr" class="nicescroll-rails nicescroll-rails-hr" style="height: 8px; z-index: 892; top: 649px; left: 0px; position: fixed; cursor: default; display: none; width: 242px; opacity: 0;"><div class="nicescroll-cursors" style="position: absolute; top: 0px; height: 6px; width: 250px; background-color: rgb(66, 66, 66); border: 1px solid rgb(255, 255, 255); background-clip: padding-box; border-radius: 5px; left: 0px;"></div></div>
</body>
</html>